<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BDC6-L-FCY7FL3" failures="1" tests="5" name="navigatetosite.lastnameerroshandling" time="18.383" errors="0" timestamp="2022-06-27T14:10:26 IST" skipped="0">
  <testcase classname="navigatetosite.lastnameerroshandling" name="teardown" time="0.514">
    <failure message="The following asserts failed:
	input Field error message displayed is wrongly expected [size must be between 3 and 18
Firstname should not be blank] but found [size must be between 3 and 30
Lastname should not be blank]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
input Field error message displayed is wrongly expected [size must be between 3 and 18
Firstname should not be blank] but found [size must be between 3 and 30
Lastname should not be blank]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at common.BaseTest.teardown(BaseTest.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:645)
at org.testng.TestRunner.afterRun(TestRunner.java:893)
at org.testng.TestRunner.run(TestRunner.java:606)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- teardown -->
  <system-out/>
  <testcase classname="navigatetosite.lastnameerroshandling" name="ScrollingIntoFormPage" time="0.199"/>
  <system-out/>
  <testcase classname="navigatetosite.lastnameerroshandling" name="InputFiledsErrors" time="1.701"/>
  <system-out/>
  <testcase classname="navigatetosite.lastnameerroshandling" name="LastnameFilederros" time="5.800"/>
  <system-out/>
  <testcase classname="navigatetosite.lastnameerroshandling" name="inputerro1" time="10.169"/>
  <system-out/>
</testsuite> <!-- navigatetosite.lastnameerroshandling -->
